### ISSUE TITLE
Huge method in Java project count due to kotlin

### ISSUE THREAD

**Issue by remcomokveld** [nitrico/LastAdapter#12]
I love the idea of this library and I understand that it is very nice to develop it in Kotlin. However, due to the use of kotlin a dependency on the kotlin-stdlib is added which causes 5000 extra methods in the dex and unfurtunately that makes it impossible for me to use. Would be great to have a Java variant as well for those of us who are not joining the kotlin hype (yet)

**Comment by nitrico** [comment]
Hi @remcomokveld,

Yes, I'm aware of that. The problem here is that started the project for myself before I decided to publish it, that's one of the reasons why it is written it Kotlin. It shouldn't be too hard to port it to Java but maintaining the two projects doesn't make too much sense. 

I can consider making the core of the lib in Java and then have another optional package to add the Kotlin-only features, but not sure about that yet.

Thanks for the comment.

**Comment by remcomokveld** [comment]
Okay, I understand. Great project though!

**Comment by nitrico** [comment]
Thanks :)
